name: MineBlockPluginManager
main: org.flyingteam.mineblock.plugman.PlugMan
version: 2.1.7
description: MineBlock Plugin manager
author: rylinaux, DreamVoid
api-version: 1.13
commands:
  mpm:
    description: Manage plugins.
    permission: mineblock.pluginmanager.help
    usage: /mpm (help|dump)
           /mpm list [-v]
           /mpm check <plugin|all> [-f]
           /mpm lookup <command>
           /mpm (enable|disable|restart) <plugin|all>
           /mpm (info|usage|load|reload|unload) <plugin>
permissions:
  mineblock.pluginmanager.admin:
    description: Allows use of all PlugMan commands.
    default: op
    children:
      mineblock.pluginmanager.update: true
      mineblock.pluginmanager.help: true
      mineblock.pluginmanager.list: true
      mineblock.pluginmanager.dump: true
      mineblock.pluginmanager.info: true
      mineblock.pluginmanager.usage: true
      mineblock.pluginmanager.lookup: true
      mineblock.pluginmanager.enable: true
      mineblock.pluginmanager.enable.all: true
      mineblock.pluginmanager.disable: true
      mineblock.pluginmanager.disable.all: true
      mineblock.pluginmanager.restart: true
      mineblock.pluginmanager.restart.all: true
      mineblock.pluginmanager.load: true
      mineblock.pluginmanager.reload: true
      mineblock.pluginmanager.unload: true
      mineblock.pluginmanager.check: true
      mineblock.pluginmanager.check.all: true
  mineblock.pluginmanager.update:
    description: Allows the player to see the update alerts.
    default: op
  mineblock.pluginmanager.help:
    description: Allows use of the help command.
    default: op
  mineblock.pluginmanager.list:
    description: Allows use of the list command.
    default: op
  mineblock.pluginmanager.dump:
    description: Allows use of the dump command.
    default: op
  mineblock.pluginmanager.info:
    description: Allows use of the info command.
    default: op
  mineblock.pluginmanager.usage:
    description: Allows use of the usage command.
    default: op
  mineblock.pluginmanager.lookup:
    description: Allows use of the lookup command.
    default: op
  mineblock.pluginmanager.enable:
    description: Allows use of the enable command.
    default: op
  mineblock.pluginmanager.enable.all:
    description: Allows use of the enable all command.
    default: op
  mineblock.pluginmanager.disable:
    description: Allows use of the disable command.
    default: op
  mineblock.pluginmanager.disable.all:
    description: Allows use of the disable all command.
    default: op
  mineblock.pluginmanager.restart:
    description: Allows use of the restart command.
    default: op
  mineblock.pluginmanager.restart.all:
    description: Allows use of the restart all command.
    default: op
  mineblock.pluginmanager.load:
    description: Allows use of the load command.
    default: op
  mineblock.pluginmanager.reload:
    description: Allows use of the reload command.
    default: op
  mineblock.pluginmanager.unload:
    description: Allows use of the unload command.
    default: op
  mineblock.pluginmanager.check:
    description: Allows use of the check command.
    default: op
  mineblock.pluginmanager.check.all:
    description: Allows use of the check all command.
    default: op
